### ISSUE TITLE
Provide vX, vX.Y tags/branches besides vX.Y.Z with automation

### ISSUE THREAD

**Issue by consideRatio** [follow-redirects/follow-redirects#239]
Thank you everyone involved for this action! :heart:

It can be helpful for users of actions if the actions expose `vX` and `vX.Y` tags/branches besides the `vX.Y.Z` tags/branches. This makes version bump PRs like https://github.com/jupyterhub/jupyterhub/pull/4670 unessecary if we simply had pinned to `v1` instead of `v1.15.2`. In practice as a user of actions, I prefer to only version control pinning to the major version and only review those changes, and pinning to `vX` would accomplish that.

This is a github workflow that would resolve this issue using the action https://github.com/Actions-R-Us/actions-tagger.

```yaml
name: Update vX and vX.Y tags

on:
  release:
    types: [released, edited]
  push:
    tags: ["v?[0-9]+.[0-9]+.[0-9]+"]

jobs:
  actions-tagger:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: Actions-R-Us/actions-tagger@v2
```
